# Generated by Django 2.2.5 on 2020-05-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
            ],
        ),
    ]
